Add/Update translations

diff --git a/cmdline/llxamp-install b/cmdline/llxamp-install
--- a/cmdline/llxamp-install
+++ b/cmdline/llxamp-install
@@ -17,24 +17,26 @@
 # You should have received a copy of the GNU General Public License
 # along with LLXAMP.  If not, see <http://www.gnu.org/licenses/>.
 
+export TEXTDOMAIN="llxamp-cmdline"
+
 source /usr/lib/llxamp/environ-cmdline
 
 help_menu(){
     echo
-    echo "Usage:"
+    echo $(gettext "Usage"):
     echo
-    echo "$program [-p <file_pack>] [-t <target>] [-f] [-h]"
-    echo "  -f: force overwrite target"
-    echo "  -h: this help"
-    echo "  defaults:"
-    echo "    <file_pack>: $file_pack"
-    echo "    <target>: $rptarget"
+    echo "$program [-p <$(gettext "file_pack")>] [-t <$(gettext "target")>] [-f] [-h]"
+    echo "  -f: $(gettext "force overwrite target")"
+    echo "  -h: $(gettext "this help")"
+    echo "  $(gettext "defaults"):"
+    echo "    <$(gettext "file_pack")>: $file_pack"
+    echo "    <$(gettext "target")>: $rptarget"
     echo
 }
 
 error_menu(){
     echo
-    echo Error $1
+    echo $(gettext "Error") $1
     help_menu
     exit 1
 }
@@ -42,7 +44,7 @@ error_menu(){
 execute(){
     $@
     if [ $? -ne 0 ]; then
-        echo "Error executing '$@', aborting operation"
+        echo "$(gettext "Error executing") '$@', $(gettext "aborting operation")"
         exit 1
     fi
 }
@@ -51,7 +53,7 @@ execute_to_tempfile(){
     tmpfile=$(mktemp)
     $@ > $tmpfile
     if [ $? -ne 0 ]; then
-        echo "Error executing '$@', aborting operation"
+        echo "$(gettext "Error executing") '$@', $(gettext "aborting operation")"
         exit 1
     fi
     echo "$tmpfile"
@@ -60,7 +62,7 @@ execute_to_tempfile(){
 execute_silent(){
     $@ >/dev/null 2>&1
     if [ $? -ne 0 ]; then
-        echo "Error executing '$@', aborting operation"
+        echo "$(gettext "Error executing") '$@', $(gettext "aborting operation")"
         exit 1
     fi
 }
@@ -90,10 +92,10 @@ get_versions(){
 }
 
 make_change_text(){
-    echo Patching text files
+    echo $(gettext "Patching text files")
     export LC_ALL=C
     components="httpd php"
-    [ ! -e "$rptarget" ] && error_menu "invalid target"
+    [ ! -e "$rptarget" ] && error_menu "$(gettext "invalid target")"
     pushd $rptarget >/dev/null
 
     for component in $components; do
@@ -111,10 +113,10 @@ make_change_text(){
 }
 
 make_change_bin(){
-    echo Patching binary files
+    echo $(gettext "Patching binary files")
     export LC_ALL=C
     components="httpd php"
-    [ ! -e "$rptarget" ] && error_menu "invalid target"
+    [ ! -e "$rptarget" ] && error_menu "$(gettext "invalid target")"
     pushd $rptarget >/dev/null
     declare -a found_bins_with_tag
     for component in $components; do
@@ -145,21 +147,21 @@ make_change_bin(){
 }
 
 write_httpd_conf(){
-    [ ! -e "$rptarget" ] && error_menu "invalid target"
+    [ ! -e "$rptarget" ] && error_menu "$(gettext "invalid target")"
     sed -r -e "s|@@LLXAMP_BASEPATH@@|$rptarget|g" -e "s|@@LLXAMP_PORT@@|$DEFAULT_PORT|g" -e "s|@@LLXAMP_USER@@|$(whoami)|g" -e "s|@@LLXAMP_SERVERNAME@@|$(hostname)|g" "$TEMPLATES_DIR"/httpd.conf > $rptarget/httpd/conf/httpd.conf
     sed -r -e "s|@@LLXAMP_BASEPATH@@|$rptarget|g" -e "s|@@LLXAMP_SSL_PORT@@|$DEFAULT_SSL_PORT|g" -e "s|@@LLXAMP_USER@@|$(whoami)|g" -e "s|@@LLXAMP_SERVERNAME@@|$(hostname)|g" "$TEMPLATES_DIR"/httpd-ssl.conf > $rptarget/httpd/conf/httpd-ssl.conf
 }
 
 include_php_samples(){
     [ ! -e "$rptarget" ] && error_menu "invalid target"
-    echo Including PHP sample pages
+    echo $(gettext "Including PHP sample pages")
     cp "$TEMPLATES_DIR"/db.php $rptarget/httpd/htdocs/
     cp "$TEMPLATES_DIR"/info.php $rptarget/httpd/htdocs/
 }
 
 configure_mysql(){
     [ ! -e "$rptarget" ] && error_menu "invalid target"
-    echo "Configuring MariaDB"
+    echo $(gettext "Configuring MariaDB")
     if [ -n "$HAVE_MARIADB" ];then
         suffix=mariadb
     else
@@ -190,18 +192,18 @@ configure_mysql2(){
         installdb=mysql_install_db
         user=root
     fi
-    echo Installing initial database
+    echo $(gettext "Installing initial database")
     execute_silent $rptarget/$suffix/scripts/$installdb --basedir=$rptarget/$suffix --datadir=$rptarget/$suffix/data --no-defaults --user=$(whoami)
-    echo Starting database
+    echo $(gettext "Starting database")
     execute_silent bash $startup_scripts/llxamp-start-mysql
     while ! $rptarget/$suffix/bin/$suffix --defaults-file=$rptarget/$suffix/conf/my.cnf --user=$user -e 'status' > /dev/null 2>&1; do
         sleep 1
     done
-    echo Creating test table
+    echo $(gettext "Creating test table")
     execute_silent $rptarget/$suffix/bin/$suffix --defaults-file=$rptarget/$suffix/conf/my.cnf --user=$user < "$TEMPLATES_DIR"/create_table.sql
-    echo Securing Mysql installation
+    echo $(gettext "Securing Mysql installation")
     execute_silent $rptarget/$suffix/bin/$suffix --defaults-file=$rptarget/$suffix/conf/my.cnf --user=$user < "$TEMPLATES_DIR"/$suffix-secure_installation.sql
-    echo Stopping database
+    echo $(gettext "Stopping database")
     execute bash $startup_scripts/llxamp-stop-mysql
     truncate -s 0 $rptarget/$suffix/var/log/*log
 }
@@ -210,7 +212,7 @@ write_start_scripts(){
     [ ! -e "$rptarget" ] && error_menu "invalid target"
     [ ! -e "$startup_scripts" ] && mkdir -p "$startup_scripts"
 
-    echo Writting start/stop scripts into "$rptarget"
+    echo $(gettext "Writting start/stop scripts into") "$rptarget"
 
     for script in "$TEMPLATES_DIR"/llxamp-*; do
         sed -r -e "s|@@LLXAMP_BASEPATH@@|$rptarget|g" -e "s|@@LLXAMP_PORT@@|$DEFAULT_PORT|g" -e "s|@@LLXAMP_SSL_PORT@@|$DEFAULT_SSL_PORT|g" "$script" > "$startup_scripts/$(basename $script)"
@@ -227,7 +229,7 @@ create_target_dir(){
     pkill -9 -f httpd > /dev/null 2>&1
     pkill -9 -f $suffix > /dev/null 2>&1
     if [ ! -e "$rptarget" ]; then
-        mkdir -p "$rptarget" ||  error_menu "Invalid parameter '$target'"
+        mkdir -p "$rptarget" ||  error_menu "$(gettext "Invalid parameter") '$target'"
     fi
     mkdir -p $HOME/.llxamp/{work,upper}
     if [ -e "$rptarget/mysql/data" ]; then
@@ -242,15 +244,15 @@ test_install_pack(){
         suffix=mysql
     fi
     need="build-tag httpd php mysql httpd/htdocs/phpMyAdmin"
-    [ ! -e "$rpfile_pack" ] && error_menu "invalid install-pack"
+    [ ! -e "$rpfile_pack" ] && error_menu "$(gettext "invalid install-pack")"
     echo Testing archive "$rpfile_pack"
     tmpfile=$(execute_to_tempfile tar -ztf "$rpfile_pack")
     sed -r 's|^[.]/(.*)|\1|g' $tmpfile > $tmpfile.new
     for n in $need; do
         if grep -s $n $tmpfile.new > /dev/null 2>&1; then
-            echo "$(basename $n) found!"
+            echo "$(basename $n) $(gettext "found!")"
         else
-            error_menu "$(basename $n) not found!"
+            error_menu "$(basename $n) $(gettext "not found!")"
         fi
     done
 }
@@ -260,33 +262,33 @@ decompress_pack(){
     [ ! -e "$rptarget" -o ! -e "$PACK_DIR" ] && error_menu "invalid target or install-pack"
     # echo "Decompressing archive into '$rptarget'"
     # execute tar -zxf "$rpfile_pack" -C "$rptarget"
-    echo "Mounting archive into '$rptarget' with copy-on-write"
+    echo "$(gettext "Mounting archive into") '$rptarget' $(gettext "with copy-on-write")"
     mounted=$(findmnt -l -o TARGET | grep "$rptarget")
     if [ -n "$mounted" ];then
-        echo "Remount '$rptarget' needed"
-        echo "Killing procs using '$rptarget'"
+        echo "$(gettext "Remount needed on"): '$rptarget'"
+        echo "$(gettext "Killing procs using") '$rptarget'"
         pids=$(lsof -u $(id -u)|grep "$HOME/llxamp"|awk '{print $2}'|sort|uniq|xargs)
         if [ -n "$pids" ]; then
-            echo "Detected pids $pids"
+            echo "$(gettext "Detected pids") $pids"
             kill -9 $pids
         fi
         # Too aggresive !
         # fuser -mk "$rptarget" > /dev/null 2>&1
         sleep 2
-        echo "Mounting '$rptarget'"
+        echo "$(gettext "Mounting") '$rptarget'"
         fusermount -uz "$rptarget"
         sleep 2
-        [ -e "$HOME/.llxamp/upper" ] && echo "Removing previous cow " && rm -rf $HOME/.llxamp/upper
+        [ -e "$HOME/.llxamp/upper" ] && echo $(gettext "Removing previous cow") && rm -rf $HOME/.llxamp/upper
         mkdir -p $HOME/.llxamp/upper
     fi
     mounted=$(findmnt -l -o TARGET | grep "$rptarget")
     if [ -z "$mounted" ];then
         set -e
         if [ -e "$PACK_DIR" -a -e "$HOME/.llxamp/upper" -a -e "$HOME/.llxamp/work" ]; then
-            [ -e "$HOME/.llxamp/upper" ] && echo "Removing previous cow " && rm -rf $HOME/.llxamp/upper && mkdir -p $HOME/.llxamp/upper
+            [ -e "$HOME/.llxamp/upper" ] && echo $(gettext "Removing previous cow") && rm -rf $HOME/.llxamp/upper && mkdir -p $HOME/.llxamp/upper
             fuse-overlayfs -olowerdir=$PACK_DIR,upperdir=$HOME/.llxamp/upper,workdir=$HOME/.llxamp/work,squash_to_uid=$(id -u),squash_to_gid=$(id -g) "$rptarget" >/dev/null 2>&1
         else
-            echo "Can't mount overlay"
+            echo $(gettext "Can't mount overlay")
             exit 1
         fi
         set +e
@@ -294,15 +296,15 @@ decompress_pack(){
 }
 
 read_tag(){
-    [ ! -e "$rptarget" ] && error_menu "invalid target"
-    echo "Reading tag"
+    [ ! -e "$rptarget" ] && error_menu "$(gettext "invalid target")"
+    echo "$(gettext "Reading tag")"
     TAG=$(cat "$rptarget/build-tag")
-    [ -z "$TAG" ] && error_menu "Empty tag"
+    [ -z "$TAG" ] && error_menu "$(gettext "Empty tag")"
     rm "$rptarget/build-tag"
 }
 
 configure_user_path(){
-    echo "Configuring user path"
+    echo "$(gettext "Configuring user path")"
     if ! grep -s 'LLXAMP_PATH' $HOME/.bashrc > /dev/null 2>&1; then
         echo "LLXAMP_PATH=\"$startup_scripts\"" >> $HOME/.bashrc
         echo 'export PATH="$LLXAMP_PATH:$PATH"' >> $HOME/.bashrc
@@ -310,13 +312,13 @@ configure_user_path(){
 }
 
 gen_openssl_certs(){
-    [ ! -e "$rptarget" ] && error_menu "invalid target"
+    [ ! -e "$rptarget" ] && error_menu "$(gettext "invalid target")"
     echo Generating OpenSSL certificates
     execute_silent openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "$rptarget"/httpd/conf/server.key -out "$rptarget"/httpd/conf/server.crt -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
 }
 
 fix_missing_php_ini(){
-    [ ! -e "$rptarget" ] && error_menu "invalid target"
+    [ ! -e "$rptarget" ] && error_menu "$(gettext "invalid target")"
     oFS=$IFS
     IFS=' '
     php_files="php.ini-development php.ini-production"
@@ -339,17 +341,17 @@ fix_missing_php_ini(){
 }
 
 print_info(){
-    echo Finished!
+    echo $(gettext "Finished!")
     echo
-    echo 'Start services with:'
+    echo $(gettext "Start services with:")
     echo '  $ llxamp-start'
-    echo 'View initial page served with:'
+    echo $(gettext "View initial page served with:")
     echo '  $ llxamp-open-browser'
-    echo 'View with SSL phpMyAdmin initial page with:'
+    echo $(gettext "View with SSL phpMyAdmin initial page with:")
     echo '  $ llxamp-open-browser-ssl /phpMyAdmin/index.php  #(default_username=root, default_root password=root)'
-    echo 'Stop services with:'
+    echo $(gettext "Stop services with:")
     echo '  $ llxamp-stop'
-    echo 'View more scripts pressing bash autocompletion keys:'
+    echo $(gettext "View more scripts pressing bash autocompletion keys:")
     echo '  $ llxamp<TAB_KEY><TAB_KEY>'
     echo
 }
@@ -402,14 +404,14 @@ target=${target:=$HOME/llxamp}
 rptarget=$(execute realpath "$target")
 
 if [ -e "$rptarget" -a -z "$forced" ]; then
-    error_menu "'$rptarget' exists, must be non-existent directory"
+    error_menu "'$rptarget' $(gettext "exists"), $(gettext "must be non-existent directory")"
 fi
 
 startup_scripts="$rptarget/scripts"
 
 if [ ! -e "/usr/lib/llxamp/pack" ]; then
     if [ -z "$rpfile_pack" -o ! -e "$rpfile_pack" ]; then
-        llxamp-download-install-pack || error_menu "Invalid pack file"
+        llxamp-download-install-pack || error_menu "$(gettext "Invalid pack file")"
         [ -e "/tmp/llxamp-install-pack/install-pack.tgz" ] && rpfile_pack="/tmp/llxamp-install-pack/install-pack.tgz"
     fi
 fi
